"""add risk_score to analyses

Revision ID: 3cc9cb43e9e6
Revises: ddee9423a6c1
Create Date: 2026-08-08 19:36:42.471305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc9cb43e9e6'
down_revision: Union[str, Sequence[str], None] = 'ddee9423a6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the autogenerated version: nullable=False with no
    # default would fail against any pre-existing rows. server_default=50
    # backfills existing analyses at the exact midpoint of the medium tier
    # -- a neutral placeholder, not a real re-score (there's no basis to
    # retroactively run the scoring formula without re-reading each row's
    # risk_indicators). Kept permanently rather than dropped afterward:
    # SQLite (tests/local dev) doesn't support ALTER COLUMN ... DROP
    # DEFAULT, and the application always supplies this column explicitly
    # on insert (routes.create_analysis), so a standing default is inert
    # in practice.
    op.add_column(
        'analyses',
        sa.Column('risk_score', sa.Integer(), nullable=False, server_default='50'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'risk_score')
    # ### end Alembic commands ###
