"""add images to listings

Revision ID: 7df6dabbd464
Revises: 3cc9cb43e9e6
Create Date: 2026-08-09 13:30:17.265564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df6dabbd464'
down_revision: Union[str, Sequence[str], None] = '3cc9cb43e9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # US-2.4 / D-12. Nullable, no backfill needed (unlike risk_score's
    # server_default) -- existing listings simply have no images, and the
    # model already types this as list[str] | None.
    op.add_column('listings', sa.Column('images', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'images')
    # ### end Alembic commands ###
