"""add price_plausibility to analyses

Revision ID: ecb69044639d
Revises: ddee9423a6c1
Create Date: 2026-08-08 18:59:39.839433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb69044639d'
down_revision: Union[str, Sequence[str], None] = 'ddee9423a6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the autogenerated version: nullable=False with no
    # default would fail against any pre-existing rows. server_default
    # backfills existing analyses as 'plausible' (a placeholder, not a
    # real re-assessment -- there's no basis to retroactively classify
    # old rows). Kept permanently rather than dropped afterward: SQLite
    # (used for tests/local dev) doesn't support ALTER COLUMN ... DROP
    # DEFAULT, and the application always supplies this column explicitly
    # on insert (routes.create_analysis), so a standing default is inert
    # in practice, not a loophole.
    op.add_column(
        'analyses',
        sa.Column('price_plausibility', sa.String(length=20), nullable=False, server_default='plausible'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'price_plausibility')
    # ### end Alembic commands ###
